<?php
namespace API\Controllers;

use API\Model\Fund;
use core\Controller;
use core\Input;
use API\Model\Users;
use core\FH;
use core\http\Middleware\Middleware;
use core\Model as CoreModel;
use core\Response;
use database\DataBase;
use core\http\Middleware\IndexMiddleware;
use core\Call\Utility\TVcalls;
use core\Call\Utility\AirtimeCall;
use core\Helper;
use core\Helper\Help;

class TvController extends Controller {
  private $db,$help, $model,$resp, $middleware,$airtime, $input,$indexMiddleware, $TVuser,$fh;
  
  public function __construct($controller, $action){
    parent::__construct($controller, $action);
    $this->db = new DataBase();
    $this->model = new coreModel($this->tabl);
    $this->middleware = new Middleware();
    $this->fh = new FH();
    $this->input = new Input();
    $this->indexMiddleware = $GLOBALS['indexMiddleware'];
    $this->resp = new Response;
    $this->TVuser = new TVcalls();
    $this->airtime = new AirtimeCall();
    $this->help = new Help();
  }

  public function tv_userverifyAction(){
    if(!$this->input->isPost()) return $this->resp->SendResponse(
      403, false, POST_MSG);
    if(!$this->indexMiddleware->isUser())return $this->resp->SendResponse(
      401, false, ACL_MSG);
    
    $userid = FH::sanitize($_REQUEST['userid']);
    $bill = FH::sanitize($_REQUEST['bill']);
    $cardNo = FH::sanitize($_REQUEST['card_no']);
    
    $tvRequest = $this->TVuser->validateTVUser($bill, $cardNo);
    if(!$tvRequest)return false;
    return $this->resp->SendResponse(200, true, $tvRequest);
  }

  public function ds_go_tvAction(){
    if(!$this->input->isPost()) return $this->resp->SendResponse(403, false, POST_MSG);
    if(!$this->indexMiddleware->isUser()) return $this->resp->SendResponse(401, false, ACL_MSG);

    //handle inputs 
    $phone = FH::sanitize($_REQUEST['phone']);
    $amount = FH::sanitize($_REQUEST['amount']);
    $smartCardNo = FH::sanitize($_REQUEST['cardno']);
    $customerName = FH::sanitize($_REQUEST['customerName']);
    $invoice = FH::sanitize($_REQUEST['invoice']);
    $billType = FH::sanitize($_REQUEST['billtype']);
    /**
     * The customerRef here is generated by our vendor system 
     * during customer validation. The front end will have to save it 
     * in state and reuse it when calling this API. The backend will 
     * use it as TRANSACTION REFERENCE instead of generating a new one.
     */
    $customerRef = FH::sanitize($_REQUEST['coustomer_ref']);
    $dateTime = $this->help->dateTimeNow();
    //instantiate in database before making api call
    $fields =[
      'username'=>$this->indexMiddleware->loggedUser(),'phone'=>$phone,
      'amount'=>$amount,'smartcardno'=>$smartCardNo,
      'customername'=>$customerName,'customerRef'=>$customerRef, 
      'invoice'=>$invoice,'billtype'=>$billType, 
      'status'=>'initiated', 'date_time'=>$dateTime
    ];
    if(!$this->model->insert($fields))//HIGH PRIORITY ERROR LOG 
    return $this->resp->SendResponse(
      500, false, 'There is a problem. Try later please.'
    );
    //Make api call
    $tvSubRequest = $this->TVuser->gotv_dstvRecharge($phone, $smartCardNo, $amount,$customerName, $invoice, $billType, $customerRef);
    //process the outcome 

    //update the database 

    //return final message
  }

  /**
   * 
   */
  public function complet_multichoiceAction(){

  }

  public function startimeAction(){
    if(!$this->input->isPost()) return $this->resp->SendResponse(
      403, false,POST_MSG);
    if(!$this->indexMiddleware->isUser()) return $this->resp->SendResponse(
      401, false, ACL_MSG);
    
    //handle inputs
    $jsonData = file_get_contents('input://php');
    $data = json_decode($jsonData);
    $sanitized = FH::arraySanitize($data);
    //set up the fields
    $fields = [
      'username'=>$this->indexMiddleware->loggedUser(), 'amount'=>$sanitized['amount'],
      'phone'=>$sanitized['phone'], 'smartcardno'=>$sanitized['smartcard']
    ];
    //insert into database before making API all.
    if(!$this->model->insert($fields)) //HIGH PRIORITY ERROR LOG
    return $this->resp->SendResponse(500, false, 'There is a problem. Please try again later.');
    //API CALL 
    $starTimeRequest = $this->TVuser->starTimeRecharge();
    //handle error

    //if success update database 

    //return final message
  }

  public function startime_completeAction(){
    
  }
}