-- MySQL Script generated by MySQL Workbench
-- Mon Jun 14 14:58:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema digitmoni_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema digitmoni_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `digitmoni_app` DEFAULT CHARACTER SET utf8 ;
USE `digitmoni_app` ;

-- -----------------------------------------------------
-- Table `digitmoni_app`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `addres` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `acl` TEXT(45) NULL,
  `entry_code` VARCHAR(45) NULL,
  `ref_code` VARCHAR(45) NULL,
  `acc_type` ENUM('member', 'partner') NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`transactions` (
  `idtransaction` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `amount` DECIMAL(7,3) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `reference` VARCHAR(45) NOT NULL,
  `purpose` VARCHAR(250) NULL,
  `transact_date` DATETIME(5) NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idtransaction`),
  UNIQUE INDEX `reference_UNIQUE` (`reference` ASC) VISIBLE,
  UNIQUE INDEX `idtransaction_UNIQUE` (`idtransaction` ASC) VISIBLE,
  INDEX `fk_transactions_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `digitmoni_app`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`dstv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`dstv` (
  `iddstv` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `bouquet` VARCHAR(150) NULL,
  `dstv_card_no` VARCHAR(45) NULL,
  `reference` VARCHAR(45) NULL,
  PRIMARY KEY (`iddstv`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`gotv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`gotv` (
  `idgotv` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `bouquet` VARCHAR(150) NOT NULL,
  `gotvcol` VARCHAR(45) NOT NULL,
  `gotv_IUC_on` VARCHAR(45) NULL,
  `reference` VARCHAR(45) NULL,
  PRIMARY KEY (`idgotv`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`startime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`startime` (
  `idstartime` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `bouquet` VARCHAR(150) NOT NULL,
  `startime_card_no` VARCHAR(45) NULL,
  `reference` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstartime`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`data` (
  `idglo_data` INT NOT NULL AUTO_INCREMENT,
  `network` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `reference` VARCHAR(45) NULL,
  PRIMARY KEY (`idglo_data`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`airtimes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`airtimes` (
  `idmtn_airtime` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `reference` VARCHAR(45) NOT NULL,
  `network` VARCHAR(45) NULL,
  PRIMARY KEY (`idmtn_airtime`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`images` (
  `idimages` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `filename` VARCHAR(45) NULL,
  `mimetype` VARCHAR(45) NULL,
  `imagescol` VARCHAR(45) NULL,
  `users_idusers` INT NOT NULL,
  UNIQUE INDEX `idimages_UNIQUE` (`idimages` ASC) VISIBLE,
  PRIMARY KEY (`users_idusers`),
  CONSTRAINT `fk_images_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `digitmoni_app`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`referrals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`referrals` (
  `idreferrals` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `compensation` DECIMAL(6,3) NULL,
  PRIMARY KEY (`idreferrals`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`acc_type_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`acc_type_rule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acc_name` VARCHAR(45) NULL,
  `referral_interest` INT NULL,
  `purchase_disc` INT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`paid_partners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`paid_partners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `periodic` VARCHAR(45) NOT NULL,
  `expiration` VARCHAR(45) NULL,
  `users_idusers` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`users_idusers`),
  CONSTRAINT `fk_paid_partners_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `digitmoni_app`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`wallet_fund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`wallet_fund` (
  `idwallet_fund` INT NOT NULL AUTO_INCREMENT,
  `acc_bal` DECIMAL(7,3) NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idwallet_fund`, `users_idusers`),
  UNIQUE INDEX `idwallet_fund_UNIQUE` (`idwallet_fund` ASC) VISIBLE,
  INDEX `fk_wallet_fund_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_wallet_fund_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `digitmoni_app`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`investment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`investment` (
  `idinvestment` INT NOT NULL AUTO_INCREMENT,
  `option_name` VARCHAR(45) NOT NULL,
  `state` ENUM('running', 'disable') NULL,
  `flex_interest` DECIMAL(2,3) NULL,
  `fixed_interest` DECIMAL(2,3) NULL,
  `min_amt` DECIMAL(8,3) NULL,
  `max_amt` DECIMAL(8,3) NULL,
  `min_duration` VARCHAR(45) NOT NULL,
  `rollover` ENUM('yes', 'no') NOT NULL,
  `cancel_cost` DECIMAL(2,3) NULL,
  PRIMARY KEY (`idinvestment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`users_investment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`users_investment` (
  `idinvestment` INT NOT NULL,
  `idusers` INT NOT NULL,
  `user_inv_id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(5) NOT NULL,
  `matures_on` DATETIME(5) NOT NULL,
  `inv_reference` VARCHAR(45) NOT NULL,
  `status` ENUM('active', 'cancelled') NOT NULL,
  PRIMARY KEY (`idinvestment`, `idusers`),
  INDEX `fk_investment_has_users_users1_idx` (`idusers` ASC) VISIBLE,
  INDEX `fk_investment_has_users_investment1_idx` (`idinvestment` ASC) VISIBLE,
  UNIQUE INDEX `user_inv_id_UNIQUE` (`user_inv_id` ASC) VISIBLE,
  CONSTRAINT `fk_investment_has_users_investment1`
    FOREIGN KEY (`idinvestment`)
    REFERENCES `digitmoni_app`.`investment` (`idinvestment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investment_has_users_users1`
    FOREIGN KEY (`idusers`)
    REFERENCES `digitmoni_app`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`one_time_pass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`one_time_pass` (
  `id_onetime` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(45) NOT NULL,
  `user_otp` VARCHAR(45) NOT NULL,
  `users_idusers` INT NOT NULL,
  UNIQUE INDEX `id_onetime_UNIQUE` (`id_onetime` ASC) VISIBLE,
  PRIMARY KEY (`users_idusers`),
  CONSTRAINT `fk_one_time_pass_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `digitmoni_app`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`user_details` (
  `iduser_details` INT NOT NULL AUTO_INCREMENT,
  `suspended_by` VARCHAR(45) NULL,
  `suspended_at` TIMESTAMP(45) NOT NULL,
  `agreed_terms` ENUM('YES', 'NO') NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`users_idusers`),
  CONSTRAINT `fk_user_details_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `digitmoni_app`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`cards` (
  `idcredentials` INT NOT NULL AUTO_INCREMENT,
  `card_no` VARCHAR(45) NULL,
  `auth` VARCHAR(5) NULL,
  `card_exp` VARCHAR(45) NULL,
  `name_on_card` VARCHAR(60) NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`users_idusers`),
  CONSTRAINT `fk_cards_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `digitmoni_app`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`user_bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`user_bank` (
  `iduser_bank` INT NOT NULL AUTO_INCREMENT,
  `bank_name` VARCHAR(45) NOT NULL,
  `acc_no` VARCHAR(45) NOT NULL,
  `acc_name` VARCHAR(60) NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`users_idusers`),
  CONSTRAINT `fk_user_bank_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `digitmoni_app`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitmoni_app`.`session_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitmoni_app`.`session_tb` (
  `idsession_tb` INT NOT NULL AUTO_INCREMENT,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idsession_tb`, `users_idusers`),
  INDEX `fk_session_tb_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_session_tb_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `digitmoni_app`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
